### ISSUE TITLE
Provide an API for linking machine state and LitElement.properties

### ISSUE THREAD

**Issue by calebdwilliams** [matthewp/lit-robot#4]
Many users will want the element's state to be reflected by and reflective of the element's attributes. There should be an API that would link the transitions between the state machine and the properties/attributes of the element itself. I the README demo code, an element author might still want the `toggle` state to be reflected by an attribute (so that `MutationObserver` can listen for changes or for any other reason).

**Comment by matthewp** [comment]
Hey @calebdwilliams. There's a way to set the element on the machine context like so: https://thisrobot.life/integrations/lit-robot.html#setting-the-element-on-context

Using that you can modify the element (like set properties) within state transitions. I'm not sure if that covers what you want or not. If not can you give an example of what kind of API you're looking for?

**Comment by calebdwilliams** [comment]
Hey thanks for taking the time to look at this. [Here's a demo of what you've proposed](https://codepen.io/calebdwilliams/pen/GRKaRmb). What I would expect is to see the `toggle` attribute added and removed from the element in the developer tools.

**Comment by matthewp** [comment]
I think I need to update those docs because they don't really explain what to do with `element`. 

I updated your example to show how you can do this: https://codepen.io/matthewp/pen/MWgdWzO?editors=1010

Having the element on the service's context allows you to do side-effects in transitions. That's how I would achieve what you want to do, today.

Setting booleans to represent machine state is somewhat common of an ask so maybe we could simplify this somehow?

**Comment by matthewp** [comment]
It's not obvious in robot that you can do side-effects as part of the machine's lifecycle. I'm adding `action` since that's a fairly common thing to want to do (I've needed many times myself so far).

https://github.com/matthewp/robot/pull/59

**Comment by matthewp** [comment]
This package has moved to the main Robot repository. Please file an issue there if you'd still like to discuss this issue.
